version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - nikkeyl

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - nikkeyl
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
