name: Semantic pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pull-request-title:
    name: Validate Pull Request title
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
